# Generated by Django 4.1.2 on 2022-12-16 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="team/images")),
                ("name", models.CharField(max_length=50, null=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("linked_in", models.URLField(blank=True, max_length=1000)),
                ("github", models.URLField(blank=True, max_length=1000)),
                ("research_interest", models.CharField(max_length=10000)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Senior", "Senior"),
                            ("Executive", "Executive"),
                        ],
                        default="Junior",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
