# Generated by Django 4.1.2 on 2022-12-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="research_interest",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
