# Generated by Django 4.1.2 on 2022-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_alter_staff_research_interest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=10000)),
                ("cover", models.ImageField(upload_to="media/solution")),
            ],
        ),
        migrations.CreateModel(
            name="SolutionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=10000)),
                ("cover", models.ImageField(upload_to="media/solution-category")),
            ],
        ),
        migrations.CreateModel(
            name="WhitePaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(max_length=1000, null=True)),
                ("authors", models.CharField(max_length=1000, null=True)),
                ("pdf", models.FileField(upload_to="media/white-papers")),
            ],
        ),
        migrations.AlterField(
            model_name="staff",
            name="photo",
            field=models.ImageField(upload_to="media/team"),
        ),
    ]
