# Generated by Django 4.1.2 on 2022-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_solution_solutioncategory_whitepaper_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="designation",
            field=models.CharField(default="Researcher", max_length=100),
        ),
        migrations.AlterField(
            model_name="staff",
            name="level",
            field=models.CharField(
                choices=[
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("CEO", "CEO"),
                    ("CTO", "CTO"),
                    ("Executive", "Executive"),
                ],
                default="Junior",
                max_length=100,
            ),
        ),
    ]
