# Generated by Django 4.1.2 on 2022-12-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0004_staff_designation_alter_staff_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="solution_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contents.solutioncategory",
            ),
        ),
    ]
