# Generated by Django 4.1.2 on 2022-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0008_alter_solution_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whitepaper",
            name="doi",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
