# Generated by Django 4.1.2 on 2022-12-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0009_alter_whitepaper_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solutioncategory",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff", name="hidden", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whitepaper",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
