# Generated by Django 4.1.2 on 2022-12-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contents",
            "0010_solution_hidden_solutioncategory_hidden_staff_hidden_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="whitepaper", old_name="title", new_name="tittle",
        ),
    ]
