# Generated by Django 4.1.2 on 2022-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0011_rename_title_whitepaper_tittle"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="about",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="level",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("CTO", "CTO"),
                    ("Executive", "Executive"),
                    ("Researcher", "Researcher"),
                ],
                default="Junior",
                max_length=100,
            ),
        ),
    ]
